#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ortho_5x15(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, LT(0,KC_NUM), LT(0,KC_INS), LT(0,KC_DEL), KC_6, KC_7, KC_8, KC_9, KC_0, KC_EQL, LALT_T(KC_GRV), KC_Q, KC_W, KC_F, KC_P, KC_B, LT(0,KC_P7), LT(0,KC_P8), LT(0,KC_P9), KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_MINS, LCTL_T(KC_TAB), LT(0,KC_A), LSFT_T(KC_R), LT(6,KC_S), KC_T, KC_G, LT(0,KC_P4), LT(0,KC_P5), LT(0,KC_P6), KC_M, KC_N, KC_E, KC_I, KC_O, LT(4,KC_QUOT), KC_LSFT, KC_Z, LT(0,KC_X), LT(0,KC_C), LSFT_T(KC_D), LT(0,KC_V), LT(0,KC_P1), LT(0,KC_P2), LT(0,KC_P3), KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_ENT, LCG_T(KC_LEFT), LSG_T(KC_RGHT), LT(4,KC_BSPC), KC_LCTL, LALT_T(KC_SPC), KC_LGUI, LT(5,KC_PENT), LT(4,KC_P0), LT(6,KC_PDOT), LT(7,KC_ENT), LT(5,KC_BSPC), RSFT_T(KC_DEL), KC_LBRC, KC_RBRC, KC_BSLS),
    [1] = LAYOUT_ortho_5x15(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_TRNS, KC_TRNS, KC_TRNS, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_TRNS, KC_TRNS, KC_A, KC_R, KC_S, KC_T, KC_G, KC_TRNS, KC_TRNS, KC_TRNS, KC_M, KC_N, KC_E, KC_I, KC_O, KC_TRNS, KC_TRNS, KC_Z, KC_X, KC_C, KC_D, KC_V, KC_TRNS, KC_TRNS, KC_TRNS, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [2] = LAYOUT_ortho_5x15(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_TRNS, KC_TRNS, KC_TRNS, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_TRNS, KC_TRNS, LT(0,KC_A), LSFT_T(KC_S), LT(6,KC_D), KC_F, KC_G, KC_TRNS, KC_TRNS, KC_TRNS, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_TRNS, KC_TRNS, KC_Z, LT(0,KC_X), LT(0,KC_C), LT(0,KC_V), KC_B, KC_TRNS, KC_TRNS, KC_TRNS, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [3] = LAYOUT_ortho_5x15(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_TRNS, KC_TRNS, KC_TRNS, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_TRNS, KC_TRNS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_TRNS, KC_TRNS, KC_TRNS, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_TRNS, KC_TRNS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_TRNS, KC_TRNS, KC_TRNS, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [4] = LAYOUT_ortho_5x15(MO(8), PDF(0), DF(1), PDF(2), DF(3), KC_NO, KC_MUTE, KC_VOLD, KC_VOLU, KC_INS, KC_PPLS, KC_PMNS, KC_PAST, KC_PSLS, KC_NO, MS_WHLU, KC_PGUP, KC_UP, KC_PGDN, MS_WHLD, KC_MSTP, KC_MPLY, KC_MPRV, KC_MNXT, KC_NO, KC_NO, KC_P7, KC_P8, KC_P9, KC_NUM, KC_CAPS, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P4, KC_P5, KC_P6, TG(4), KC_TRNS, LCTL(LSFT(KC_Z)), LCTL(LSFT(KC_X)), LCTL(LSFT(KC_C)), LCTL(LSFT(KC_V)), LCTL(LSFT(KC_V)), KC_PSCR, KC_BRID, KC_BRIU, KC_NO, KC_NO, KC_P1, KC_P2, KC_P3, KC_ENT, DF(0), DF(2), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSPC, KC_P0, KC_PDOT, KC_NO),
    [5] = LAYOUT_ortho_5x15(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LALT(KC_F10), LALT(KC_F11), LALT(KC_F12), KC_PSCR, KC_INS, KC_NO, KC_HOME, KC_END, KC_DEL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LALT(KC_F7), LALT(KC_F8), LALT(KC_F9), MS_WHLU, KC_PGUP, KC_UP, KC_PGDN, MS_WHLD, KC_ENT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LALT(KC_F4), LALT(KC_F5), LALT(KC_F6), LCTL(LSFT(KC_Z)), KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, TG(4), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LALT(KC_F1), LALT(KC_F2), LALT(KC_F3), LCTL(KC_Z), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), KC_NO, TG(5), KC_TRNS, KC_TRNS, KC_TRNS, LCTL(KC_LSFT), KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_NO, KC_NO, TG(6)),
    [6] = LAYOUT_ortho_5x15(KC_ESC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WBAK, KC_WFWD, KC_HOME, KC_END, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, MS_WHLL, MS_WHLU, MS_UP, MS_WHLD, MS_WHLR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, MS_ACL1, MS_ACL0, LCTL(KC_R), KC_F5, KC_NO, KC_NO, MS_LEFT, MS_DOWN, MS_RGHT, MS_ACL0, MS_ACL1, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, MS_BTN3, MS_BTN1, MS_BTN2, KC_NO, MS_ACL2, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, MS_BTN3, MS_BTN1, MS_BTN2, KC_NO, KC_NO, TG(6)),
    [7] = LAYOUT_ortho_5x15(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_END, KC_PLUS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_END, KC_LCBR, KC_RCBR, KC_COLN, KC_UNDS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_RGHT, KC_LPRN, KC_RPRN, KC_BSLS, KC_DQUO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LT, KC_GT, KC_QUES, KC_ENT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_BSPC, KC_DEL, KC_PIPE, KC_LCBR, KC_RCBR),
    [8] = LAYOUT_ortho_5x15(KC_TRNS, DF(0), DF(1), DF(2), DF(3), KC_NO, KC_NO, KC_NO, KC_PWR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, DB_TOGG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT)
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C



bool process_record_user(uint16_t keycode, keyrecord_t * record) {
  switch (keycode) {
  case LT(0, KC_P1):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_P1);
    } else if (record -> event.pressed) {
      tap_code16(KC_F1);
    }
    return false;
  case LT(0, KC_P2):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_P2);
    } else if (record -> event.pressed) {
      tap_code16(KC_F2);
    }
    return false;
  case LT(0, KC_P3):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_P3);
    } else if (record -> event.pressed) {
      tap_code16(KC_F3);
    }
    return false;
  case LT(0, KC_P4):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_P4);
    } else if (record -> event.pressed) {
      tap_code16(KC_F4);
    }
    return false;
  case LT(0, KC_P5):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_P5);
    } else if (record -> event.pressed) {
      tap_code16(KC_F5);
    }
    return false;
  case LT(0, KC_P6):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_P6);
    } else if (record -> event.pressed) {
      tap_code16(KC_F6);
    }
    return false;
  case LT(0, KC_P7):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_P7);
    } else if (record -> event.pressed) {
      tap_code16(KC_F7);
    }
    return false;
  case LT(0, KC_P8):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_P8);
    } else if (record -> event.pressed) {
      tap_code16(KC_F8);
    }
    return false;
  case LT(0, KC_P9):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_P9);
    } else if (record -> event.pressed) {
      tap_code16(KC_F9);
    }
    return false;
  case LT(0, KC_NUM):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_NUM);
    } else if (record -> event.pressed) {
      tap_code16(KC_F10);
    }
    return false;
  case LT(0, KC_INS):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_INS);
    } else if (record -> event.pressed) {
      tap_code16(KC_F11);
    }
    return false;
  case LT(0, KC_DEL):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_DEL);
    } else if (record -> event.pressed) {
      tap_code16(KC_F12);
    }
    return false;
  case LT(0, KC_SPC):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_SPC);
    } else if (record -> event.pressed) {
      tap_code16(KC_ENT);
    }
    return false;
  case LT(0, KC_A):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_A);
    } else if (record -> event.pressed) {
      tap_code16(C(KC_A));
    }
    return false;
  case LT(0, KC_X):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_X);
    } else if (record -> event.pressed) {
      tap_code16(C(KC_X));
    }
    return false;
  case LT(0, KC_C):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_C);
    } else if (record -> event.pressed) {
      tap_code16(C(KC_C));
    }
    return false;
  case LT(0, KC_V):
    if (record -> tap.count && record -> event.pressed) {
      tap_code16(KC_V);
    } else if (record -> event.pressed) {
      tap_code16(C(KC_V));
    }
    return false;
  }
  return true;
}

